export const port = "4000"
export const dbName = "student_db"
export const userName = "postgres"
export const password = "root"
export const fromMail = "cykoxoro@gmail.com"
export const subject = "Your results have been published. Please view the result in the attachment."